#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
corriger_lot1.py — A LANCER UNE SEULE FOIS depuis le Shell Render.

Premier lot de corrections issues du scan systematique de contamination
(85 articles suspects detectes, nettoyage automatique applique, 60 restants
verifies un par un contre le PDF source). Ce lot corrige les articles :
4, 8, 10, 11, 23, 43, 61, 69, 72.

Usage :
    python corriger_lot1.py
"""
import json

CHEMIN_FICHIER = "cgi2026_articles_corrige.json"

with open(CHEMIN_FICHIER, encoding="utf-8") as f:
    articles = json.load(f)

corrections = {
    "4": (
        "Art. 4.- Sont passibles de l’impôt sur\n"
        "les sociétés en raison de leurs activités:\n"
        "1° les sociétés coopératives de\n"
        "consommation, lorsqu’elles\n"
        "possèdent des établissements,\n"
        "boutiques ou magasins pour la\n"
        "vente et la livraison de denrées,\n"
        "produits ou marchandises ;\n"
        "2° les sociétés coopératives et\n"
        "unions de coopératives d’artisans ;\n"
        "3° les sociétés coopératives ouvrières de production ;\n"
        "4° Les sociétés civiles professionnelles ou immobilières quelle\n"
        "que soit leur forme qui :\n"
        "a) se livrent à une exploitation\n"
        "ou à des opérations de nature\n"
        "commerciale, industrielle ou\n"
        "artisanale, notamment :\n"
        "i) lorsqu’elles se livrent à des\n"
        "opérations d’intermédiaires\n"
        "pour l’achat ou la vente des\n"
        "immeubles ou fonds de commerce ou qui habituellement\n"
        "achètent en leur nom les\n"
        "mêmes biens en vue de les\n"
        "revendre ;\n"
        "ii) lorsqu’elles procèdent au\n"
        "lotissement et à la vente de\n"
        "terrains leur appartenant ;\n"
        "iii) lorsqu’elles donnent en\n"
        "location un établissement\n"
        "commercial ou industriel\n"
        "muni du mobilier ou du matériel nécessaire à son exploitation, que la location comprenne ou non tout ou partie\n"
        "des éléments incorporels du\n"
        "fonds de commerce ou d’industrie ;\n"
        "b) se livrent à une exploitation ou à\n"
        "des opérations économiques\n"
        "non commerciales ;\n"
        "c) comprennent parmi leurs\n"
        "membres une ou plusieurs sociétés de capitaux ;\n"
        "5° les sociétés de crédit foncier ;\n"
        "6° les adjudicataires, concessionnaires et fermiers de droits communaux ;\n"
        "7° les établissements publics, les\n"
        "organismes de l’État et des collectivités territoriales, à condition qu’ils jouissent de l’autonomie financière et se livrent à une\n"
        "activité à caractère industriel ou\n"
        "commercial et à des opérations\n"
        "à caractère lucratif ;\n"
        "8° les centres de gestion agréés\n"
        "créés sous forme commerciale;\n"
        "9° les associations et les Organisations Non Gouvernementales\n"
        "exerçant une activité à but lucratif ;\n"
        "10° les établissements privés d’enseignement général et/ou professionnel ;\n"
        "11° les sociétés de fait ;\n"
        "12° toutes autres personnes morales se livrant à une exploitation ou à des opérations à\n"
        "caractère lucratif, ou qui ne\n"
        "seraient pas assujetties à un\n"
        "autre impôt sur les revenus, y\n"
        "compris les sociétés et autres\n"
        "entités non-résidentes disposant d’un établissement stable\n"
        "au Niger.\n"
    ),
    "8": (
        "Art. 8.- 1) Les sociétés d’investissement à capital fixe pour la partie des\n"
        "bénéfices provenant des produits nets\n"
        "de leur portefeuille ou des plus-values\n"
        "qu’elles réalisent sur la vente des titres\n"
        "ou des parts sociales faisant partie de\n"
        "ce portefeuille sont exonérées de l’impôt sur les sociétés.\n"
        "2) Cette exonération est de cinq (5) ans\n"
        "à compter de la date de création de\n"
        "la société. Elle est subordonnée aux\n"
        "conditions suivantes :\n"
        "a) avoir à tout moment un minimum de 50% de la valeur nette\n"
        "du portefeuille global composé\n"
        "d’actions de sociétés non cotées en bourse ;\n"
        "b) joindre à la déclaration de résultat prévue à l’article 69, un état\n"
        "permettant d’apprécier à la fin\n"
        "de chaque année le quota de\n"
        "50% visé ci-dessus.\n"
    ),
    "10": (
        "Art. 10.- 1) Les bénéfices passibles de\n"
        "l’impôt sur les sociétés sont déterminés en tenant compte uniquement des\n"
        "bénéfices réalisés dans les entreprises\n"
        "exploitées au Niger ainsi que ceux dont\n"
        "l’imposition est attribuée au Niger par\n"
        "une convention internationale relative\n"
        "aux non doubles impositions.\n"
        "2) Sont réputées exploitées au Niger :\n"
        "a) les entreprises dont le siège social ou le lieu de direction effective est situé au Niger ;\n"
        "b) les entreprises domiciliées à\n"
        "l’étranger disposant d’un établissement stable au Niger,\n"
        "sous réserve des dispositions\n"
        "des conventions internationales relatives aux non doubles\n"
        "impositions.\n"
        "3) Le bénéfice des entreprises ne remplissant pas les conditions visées au\n"
        "paragraphe 2 est imposable au Niger\n"
        "dès lors qu’elles y réalisent des activités formant un cycle commercial\n"
        "complet.\n"
    ),
    "11": (
        "Art. 11.- 1) L’expression « établissement stable » désigne une installation\n"
        "fixe d’affaires par l’intermédiaire de laquelle l’entreprise exerce tout ou partie de son activité.\n"
        "2) Constituent notamment des établissements stables :\n"
        "a) un siège de direction ou d’exploitation ;\n"
        "b) une succursale ;\n"
        "c) un magasin de vente ;\n"
        "d) un entrepôt ;\n"
        "e) un bureau ;\n"
        "f) une usine ;\n"
        "g) un atelier ;\n"
        "h) une mine, carrière, un puits de\n"
        "pétrole ou de gaz, ou autre lieu\n"
        "d’extraction de ressources naturelles ;\n"
        "i) un chantier de construction,\n"
        "un projet de montage ou d’installation ou des activités de\n"
        "supervision liées à ce projet,\n"
        "lorsque ce chantier, ce projet\n"
        "ou ces activités ont une durée\n"
        "supérieure à trois (3) mois ;\n"
        "j) la fourniture de services par\n"
        "une entreprise agissant par\n"
        "l’intermédiaire d’employés ou\n"
        "autre personnel engagés par\n"
        "l’entreprise à cette fin, mais\n"
        "seulement lorsque des activités\n"
        "de cette nature se poursuivent\n"
        "au Niger pour une période ou\n"
        "des périodes totalisant plus de\n"
        "cent quatre-vingt-trois (183)\n"
        "jours d’une période de douze\n"
        "(12) mois commençant ou\n"
        "s’achevant au cours de l’année\n"
        "fiscale concernée.\n"
        "3) On ne considère pas qu’il y a établissement stable si :\n"
        "a) il est fait usage d’installations\n"
        "aux seules fins de stockage ou\n"
        "d’exposition de marchandises\n"
        "appartenant à l’entreprise ;\n"
        "b) des marchandises appartenant\n"
        "à l’entreprise sont entreposées\n"
        "aux seules fins de stockage ou\n"
        "d’exposition ;\n"
        "c) des marchandises appartenant\n"
        "à l’entreprise sont entreposées\n"
        "aux seules fins de transformation par une autre entreprise ;\n"
        "d) une installation fixe d’affaires\n"
        "est utilisée aux seules fins de\n"
        "publicité, de fourniture d’informations, de recherches scientifiques, ou de veille à l’exécution d’un contrat portant sur\n"
        "un brevet ou un savoir-faire\n"
        "(know-how), si ces activités ont\n"
        "un caractère préparatoire ou\n"
        "auxiliaire ;\n"
        "e) une installation fixe d’affaires\n"
        "est utilisée aux seules fins\n"
        "d’exercer, pour l’entreprise,\n"
        "toute autre activité de caractère préparatoire ou auxiliaire ;\n"
        "f) une installation fixe d’affaires\n"
        "est utilisée aux seules fins de\n"
        "l’exercice cumulé d’activités\n"
        "mentionnées aux points a) à\n"
        "e) du présent paragraphe, à\n"
        "condition que l’activité d’ensemble de l’installation fixe\n"
        "d’affaires résultant de ce cumul garde un caractère préparatoire ou auxiliaire.\n"
        "4) Une personne agissant au Niger pour le compte d’une entreprise\n"
        "non-résidente au Niger, autre qu’un\n"
        "agent jouissant d’un statut indépendant visé au point 7 ci-après, est considérée comme établissement stable :\n"
        "a) si elle dispose au Niger de pouvoirs généraux qu’elle y exerce\n"
        "habituellement lui permettant\n"
        "de négocier et de conclure des\n"
        "contrats au nom ou pour le\n"
        "compte de l’entreprise ;\n"
        "b) si elle conserve habituellement\n"
        "au Niger un stock de marchandises sur lequel elle prélève régulièrement des marchandises\n"
        "aux fins de livraison au nom ou\n"
        "pour le compte de l’entreprise.\n"
        "5) Une entreprise d’assurances ou de\n"
        "réassurances non-résidente au Niger\n"
        "est considérée comme ayant un établissement stable au Niger si elle y perçoit des primes ou assure des risques\n"
        "qui y sont courus par l’intermédiaire\n"
        "d’un employé ou par l’intermédiaire\n"
        "d’un représentant qui n’entre pas dans\n"
        "la catégorie de personnes visées au\n"
        "point 7 ci-après.\n"
        "6) On ne considère pas qu’une entreprise non-résidente au Niger a un établissement stable au Niger du seul fait\n"
        "de l’achat de marchandises pour le\n"
        "compte de l’entreprise.\n"
        "7) On ne considère pas qu’une entreprise non-résidente au Niger a un établissement stable au Niger du seul fait\n"
        "qu’elle y exerce son activité par l’entremise d’un courtier, d’un commissionnaire ou de tout autre intermédiaire\n"
        "jouissant d’un statut indépendant à\n"
        "condition que ces personnes agissent\n"
        "dans le cadre ordinaire de leur activité.\n"
    ),
    "23": (
        "Art. 23.- 1) Pour être admise en déduction, une charge doit satisfaire aux\n"
        "conditions cumulatives suivantes :\n"
        "a) être exposée dans l’intérêt direct\n"
        "de l’exploitation ou se rattacher\n"
        "à la gestion normale de l’entreprise ;\n"
        "b) correspondre à une charge effective et être appuyée de justifications suffisantes ;\n"
        "c) se traduire par une diminution\n"
        "de l’actif net de l’entreprise ;\n"
        "d) être comprise dans les charges\n"
        "de l’exercice au cours duquel\n"
        "elle a été engagée ;\n"
        "e) concourir à la formation d’un\n"
        "produit non exonéré d’impôt\n"
        "sur les sociétés ;\n"
        "f) ne pas être exclue par une disposition fiscale particulière.\n"
        "2) Par ailleurs, pour être admises en\n"
        "déduction, les factures justificatives\n"
        "des charges doivent porter les mentions obligatoires visées à l’article 802\n"
        "du présent Code, sous réserve des dérogations prévues au même article.\n"
        "3) Peuvent être admis en déduction\n"
        "du bénéfice imposable, les achats de\n"
        "produits alimentaires du cru auprès\n"
        "d’un fournisseur non immatriculé. Les\n"
        "achats doivent être matérialisés par\n"
        "un reçu, délivré par le fournisseur non\n"
        "immatriculé, qui doit être conservé\n"
        "par l’opérateur économique à titre de\n"
        "pièce justificative. Toutefois, ne sont\n"
        "concernés par cette déduction que les\n"
        "produits alimentaires non transformés\n"
        "dont la liste est annexée à la Directive 02/2009/CM/UEMOA du 27 mars\n"
        "2009, à l’exclusion des produits cités\n"
        "au point 1 de ladite liste.\n"
        "4) Nonobstant, les dispositions qui\n"
        "précèdent, toute charge d’un montant supérieur ou égal à deux millions\n"
        "(2.000.000) francs, se rapportant à une\n"
        "transaction dont le paiement n’a été\n"
        "effectué par procédé bancaire, n’est\n"
        "pas déductible.\n"
        "N’ouvre pas droit également à déduction, les charges liées aux montants\n"
        "payés par les bénéficiaires des prestations de services dont les contrats\n"
        "n’ont pas été soumis à la formalité de\n"
        "l’enregistrement prévue au point 15 de\n"
        "l’article 435 du Code Général des Impôts.\n"
        "(Modifié par Ordonnance N° 2025-44 du\n"
        "31 décembre 2025 portant Loi de Finances\n"
        "pour l’année budgétaire 2026.)\n"
    ),
    "43": (
        "Art. 43.- 1) Sont déductibles au titre\n"
        "des charges financières, les intérêts servis aux associés, à raison des\n"
        "sommes qu’ils mettent à la disposition\n"
        "de la société en sus de leur part de capital, quelle que soit la forme de la société, sous les conditions suivantes :\n"
        "a) le capital de la société est entièrement libéré ;\n"
        "b) les sommes apportées cumulées ne dépassent pas le montant des capitaux propres ;\n"
        "c) le taux d’intérêt ne dépasse pas le\n"
        "taux directeur de la Banque Centrale majoré de trois (3) points.\n"
        "2) Les intérêts payés par une entreprise exploitée au Niger auprès d’une\n"
        "autre entreprise liée au sens du point 2\n"
        "de l’article 33 du présent Code ou ceux\n"
        "découlant d’un prêt garanti par une\n"
        "entreprise liée ne sont admis en déduction que si les conditions suivantes\n"
        "sont réunies :\n"
        "a) les prêts consentis ne doivent\n"
        "pas dépasser le montant des\n"
        "capitaux propres ;\n"
        "b) les intérêts versés aux sociétés\n"
        "du groupe ou liées ne doivent\n"
        "pas dépasser le taux d’intérêt\n"
        "directeur de la Banque Centrale\n"
        "majoré de trois (3) points.\n"
        "3) Toutefois, le montant total des intérêts déductibles dus annuellement\n"
        "à raison de l’ensemble des dettes\n"
        "contractées par une entreprise exploitée au Niger auprès d’une autre entreprise liée au sens du point 2 de l’article\n"
        "33 du présent Code, est limité à 25 %\n"
        "de l’excédent brut d’exploitation tel\n"
        "qu’il est défini par la réglementation\n"
        "comptable OHADA. Les dispositions\n"
        "du présent paragraphe ne sont pas\n"
        "applicables aux banques et autres établissements financiers.\n"
        "4) Pour les banques et établissements\n"
        "financiers, le contrôle des intérêts versés aux entreprises associées ou liées\n"
        "se fait, notamment, en tenant compte :\n"
        "a) du ratio de solvabilité exigé par\n"
        "la Banque Centrale ;\n"
        "b) du ratio de solvabilité du groupe\n"
        "de la banque contrôlée ;\n"
        "c) des règles applicables en matière de prix de transfert.\n"
        "5) Aucune déduction n’est admise pour\n"
        "les intérêts qui sont versées par un\n"
        "établissement stable au siège de l’entreprise ou à l’un quelconque de ses\n"
        "autres établissements, sauf dans le\n"
        "cas d’une entreprise bancaire ou d’un\n"
        "établissement financier, comme intérêts sur des sommes prêtées à l’établissement stable sur fonds propres.\n"
        "6) Le terme « intérêts » désigne les revenus des créances de toute nature,\n"
        "assorties ou non de garanties hypothécaires ou d’une clause de participation\n"
        "aux bénéfices du débiteur, et notamment les revenus des fonds publics\n"
        "et les revenus d’obligations ou d’emprunts, y compris les primes et lots attachés à ces obligations ou emprunts.\n"
        "Les pénalités pour paiement tardif ne\n"
        "sont pas considérées comme des intérêts au sens du présent article.\n"
    ),
    "61": (
        "Art. 61.- 1) L’impôt minimum forfaitaire\n"
        "est assis annuellement sur le chiffre\n"
        "d’affaires réalisé au cours du dernier\n"
        "exercice comptable intervenu.\n"
        "2) Toutefois, pour certaines catégories\n"
        "d’activités, la base de calcul dudit impôt est la marge brute déterminée sur\n"
        "la même période. Les activités concernées par cette dérogation sont déterminées par voie règlementaire.\n"
        "3) Le chiffre d’affaires réalisé s’entend\n"
        "hors taxe sur la valeur ajoutée. Il englobe les produits accessoires, c’est-à-dire ceux réalisés à l’occasion de la\n"
        "gestion commerciale de l’entreprise\n"
        "mais ne se rattachant pas à son objet\n"
        "principal et ceux provenant de la mise\n"
        "en valeur de l’actif immobilisé.\n"
    ),
    "69": (
        "Art. 69.- Les sociétés sont tenues de\n"
        "déposer auprès des services des impôts de rattachement de leur dossier\n"
        "fiscal, en même temps que leur déclaration de résultats, en fonction de leur\n"
        "cadre comptable, les états et documents énumérés ci-dessous, revêtus\n"
        "du visa d’un professionnel comptable\n"
        "habilité à cet effet :\n"
        "a) Les sociétés et organismes\n"
        "relevant du cadre comptable\n"
        "dénommé acte uniforme sur\n"
        "le droit comptable et à l’information financière, à l’exclusion\n"
        "des états IFRS (International\n"
        "Financial Reporting Standard),\n"
        "et système comptable OHADA\n"
        "doivent joindre les documents\n"
        "comptables ci-après :\n"
        "i) le bilan ;\n"
        "ii) le compte de résultat ;\n"
        "iii) le tableau de flux de trésorerie ;\n"
        "iv) les notes annexes ;\n"
        "v) les états supplémentaires de la\n"
        "Direction Générale des Impôts\n"
        "selon les modèles prévus.\n"
        "b) Les sociétés d’assurances ou\n"
        "de réassurances, de capitalisation ou d’épargne doivent\n"
        "remettre en plus du bilan, du\n"
        "compte d’exploitation générale,\n"
        "du compte général de pertes et\n"
        "profits et du compte de résultat,\n"
        "des états supplémentaires de la\n"
        "Direction Générale des Impôts\n"
        "selon les modèles prévus, un\n"
        "double du compte rendu détaillé et des tableaux annexés par\n"
        "elles, fournis au Ministre chargé\n"
        "des Finances.\n"
        "c) Les banques et les établissements financiers sont tenus de\n"
        "produire les documents comptables ci-après :\n"
        "i) le bilan ;\n"
        "ii) le hors-bilan ;\n"
        "iii) le compte de résultat ;\n"
        "iv) les notes annexes ;\n"
        "v) les états supplémentaires de\n"
        "la Direction Générale des Impôts selon les modèles prévus.\n"
        "d) Les sociétés visées au présent article doivent produire également :\n"
        "i) la liste détaillée par catégorie des frais généraux ;\n"
        "ii) le relevé de leurs amortissements et des provisions\n"
        "constitués avec l’indication\n"
        "précise de leur objet ;\n"
        "iii) la liste des principaux clients\n"
        "et fournisseurs. La liste doit\n"
        "indiquer, pour chaque client\n"
        "ou fournisseur, le Numéro\n"
        "d’Identification Fiscale pour\n"
        "les sociétés établies au Niger, les noms ou raison sociale, l’adresse complète,\n"
        "le numéro de téléphone et\n"
        "le montant des transactions\n"
        "réalisées.\n"
        "e) Les sociétés dont le siège social est situé hors du Niger\n"
        "remettent, en plus, un exemplaire de leur bilan général.\n"
    ),
    "72": (
        "Art. 72.- 1) Les plus-values, autres que\n"
        "celles réalisées sur les marchandises,\n"
        "résultant de l’attribution d’actions ou\n"
        "de parts sociales à la suite de la fusion\n"
        "de sociétés anonymes, de sociétés\n"
        "par action simplifiée ou de sociétés à\n"
        "responsabilité limitée, sont exonérées\n"
        "de l’impôt sur les sociétés, à condition\n"
        "que la société absorbante ou nouvelle\n"
        "ait son siège social au Niger.\n"
        "2) Le même régime est applicable lorsqu’une société anonyme, une société\n"
        "par action simplifiée ou une société à\n"
        "responsabilité limitée apporte l’intégralité de son actif à deux ou plusieurs\n"
        "sociétés constituées à cette fin (cas\n"
        "de scission) ou une partie de ses éléments d’actif à une société constituée\n"
        "sous l’une de ces formes (cas d’apport\n"
        "partiel) à condition que :\n"
        "a) la (s) société(s) bénéficiaire(s)\n"
        "de l’apport ait (aient) son siège\n"
        "social au Niger ;\n"
        "b) les apports résultant de ces\n"
        "conventions prennent effet à la\n"
        "même date pour les différentes\n"
        "sociétés qui en sont bénéficiaires et entraînent dès leur réalisation (en cas de fusion ou de\n"
        "scission) la dissolution immédiate de la société apporteuse.\n"
        "3) Le même régime est applicable aux\n"
        "plus-values résultant de la transformation d’une société ou d’une association en groupement d’intérêt économique.\n"
    ),
}

nb_corriges = 0
for art in articles:
    if art["article_id"] in corrections:
        art["text"] = corrections[art["article_id"]]
        nb_corriges += 1
        print(f"Article {art['article_id']} corrigé ({len(art['text'])} caractères).")

with open(CHEMIN_FICHIER, "w", encoding="utf-8") as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"\n{nb_corriges}/9 articles corrigés (Lot 1).")
