#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
corriger_lot6.py — A LANCER UNE SEULE FOIS depuis le Shell Render.

Lot 6 : articles 643, 644, 661, 682, 683, 684, 689, 693.

Usage :
    python corriger_lot6.py
"""
import json

CHEMIN_FICHIER = "cgi2026_articles_corrige.json"

with open(CHEMIN_FICHIER, encoding="utf-8") as f:
    articles = json.load(f)

corrections = {
    "643": (
        "Art. 643.- L’Administration fiscale\n"
        "contrôle les déclarations des contribuables ainsi que les actes et documents utilisés pour l’établissement de\n"
        "l’ensemble des impôts, droits ou taxes\n"
        "mis à leur charge.\n"
    ),
    "644": (
        "Art. 644.- 1) Le contrôle formel\n"
        "consiste en un examen destiné à rectifier les erreurs matérielles apparaissant dans les déclarations souscrites.\n"
        "2) Il ne peut, en aucun cas, se traduire\n"
        "par la modification des chiffres déclarés. Il prépare le contrôle sur pièces.\n"
        "3) Les agents qui reçoivent les déclarations des contribuables procèdent, de\n"
        "leur bureau, au contrôle de ces déclarations.\n"
    ),
    "661": (
        "Art. 661.- 1) Lorsque, au cours d’un\n"
        "examen contradictoire de la situation\n"
        "fiscale personnelle, il est constaté une\n"
        "disproportion marquée entre le train\n"
        "de vie du contribuable vérifié et ses\n"
        "revenus déclarés, le montant total de\n"
        "ses impôts personnels sur le revenu\n"
        "ne peut être inférieur à un impôt de\n"
        "référence déterminé sur la base des\n"
        "éléments du train de vie.\n"
        "2) Pour l’application du point 1 ci-dessus du présent article, il est entendu\n"
        "par impôts personnels, la somme de\n"
        "l’impôt sur les bénéfices d’affaires des\n"
        "personnes physiques, de l’impôt sur le\n"
        "revenu des capitaux mobiliers, de l’impôt sur les plus-values, de l’impôt sur\n"
        "les revenus locatifs et de l’impôt sur\n"
        "les traitements et salaires acquittés au\n"
        "titre d’une même année.\n"
        "3) L’impôt de référence est calculé en\n"
        "appliquant le taux de l’impôt sur les bénéfices d’affaires sur les personnes physiques sur les éléments du train de vie\n"
        "déterminés forfaitairement comme suit :\n"
        "1) Résidences principales et secondaires en République du Niger ou hors du Niger, dépenses d’entretien et occupation : trois fois la valeur locative mensuelle. Cette valeur est majorée si la résidence comporte des piscines : par piscine, 500 000 FCFA.\n"
        "2) Verger : 200 000 FCFA par hectare.\n"
        "3) Gardien, cuisinier, jardinier et autres : 400 000 FCFA par personne.\n"
        "4) Voitures automobiles de tourisme :\n"
        "a) de puissance supérieure à 20 CV, par voiture : 3 000 000 FCFA ;\n"
        "b) de puissance comprise entre 15 et 20 CV, par voiture : 2 500 000 FCFA ;\n"
        "c) d’une puissance inférieure à 15 CV, par voiture : 2 000 000 FCFA.\n"
        "Ces valeurs subissent un abattement de 20% après un an d’usage et de 10% supplémentaires par année pendant les quatre années suivantes sans pour autant être inférieures à 500 000 FCFA. Toutefois, la base ainsi déterminée est réduite de moitié, pour les voitures qui sont affectées à titre exclusif à un usage professionnel.\n"
        "5) Bateaux de plaisance à voiles :\n"
        "a) jusqu’à trois tonneaux : 200 000 FCFA ;\n"
        "b) par tonneau au-dessus de trois jusqu’à dix : 5 000 FCFA ;\n"
        "c) au-dessus de dix tonneaux : 100 000 FCFA.\n"
        "6) Bateaux de plaisance à moteur fixe hors-bord : pour les 20 premiers chevaux, 300 000 FCFA ; par cheval-vapeur supplémentaire, 20 000 FCFA.\n"
        "7) Chevaux de course : 1 000 000 FCFA par tête.\n"
        "8) Chameaux : 100 000 FCFA par tête.\n"
        "9) Vaches : 50 000 FCFA par tête.\n"
        "10) Avions de tourisme : 20 000 000 FCFA.\n"
        "11) Voyages à l’étranger : le revenu à retenir sera fonction du coût du voyage et de la durée du séjour : frais réels par jour.\n"
        "12) Frais de subsistance : trois fois le Salaire Minimum Interprofessionnel Garanti.\n"
        "13) Frais de scolarité pour les enfants inscrits à l’étranger : frais réels.\n"
    ),
    "682": (
        "Art. 682.- Il n’est procédé à aucun redressement d’impositions antérieures\n"
        "lorsque le contribuable établit qu’il\n"
        "s’est conformé de bonne foi à une interprétation d’un texte fiscal formellement admise par l’Administration\n"
        "fiscale.\n"
    ),
    "683": (
        "Art. 683.- 1) L’Administration fiscale\n"
        "peut délivrer un rescrit fiscal exposant\n"
        "sa position concernant l’interprétation\n"
        "d’un texte fiscal ou l’application de la\n"
        "législation fiscale à une situation proposée par un contribuable.\n"
        "2) La demande doit être formulée, selon le cas :\n"
        "a) soit avant la date d’expiration du délai dont dispose le\n"
        "contribuable pour faire sa déclaration ;\n"
        "b) soit en l’absence d’obligation\n"
        "déclarative, avant la date d’exigibilité de l’impôt concerné.\n"
        "3) La demande de rescrit doit être\n"
        "adressée par écrit au Directeur Général des Impôts et contenir les informations suivantes :\n"
        "a) le nom et l’adresse du demandeur ;\n"
        "b) une présentation précise,\n"
        "complète et sincère de la situation présentée à l’Administration fiscale ;\n"
        "c) la question précise à laquelle\n"
        "le contribuable souhaite obtenir une position de l’Administration fiscale ;\n"
        "d) le texte fiscal sur la base\n"
        "duquel le demandeur saisit\n"
        "l’Administration fiscale pour\n"
        "qu’elle prenne position et\n"
        "l’analyse que le demandeur\n"
        "en fait.\n"
        "4) En cas de demande incomplète,\n"
        "l’Administration fiscale peut inviter le\n"
        "demandeur à lui fournir des informations complémentaires.\n"
        "5) L’Administration fiscale répond dans\n"
        "un délai de trois (3) mois suivant la réception de la demande ou, en cas de\n"
        "demande incomplète, suivant réception des compléments d’informations\n"
        "demandés.\n"
        "6) Le rescrit fiscal obtenu sur la situation du contribuable est opposable\n"
        "à l’Administration fiscale si les trois\n"
        "conditions suivantes sont remplies :\n"
        "a) le contribuable suit la position ou les indications communiquées par l’Administration fiscale ;\n"
        "b) le contribuable est de bonne\n"
        "foi ;\n"
        "c) la situation du contribuable\n"
        "est identique à celle sur laquelle l’Administration fiscale\n"
        "a pris position.\n"
        "7) La garantie prévue au paragraphe\n"
        "précédent cesse si :\n"
        "a) la situation du contribuable\n"
        "n’est plus identique à celle\n"
        "qu’il a présentée dans sa demande ;\n"
        "b) la législation applicable à la\n"
        "situation du contribuable a\n"
        "évolué ;\n"
        "c) l’Administration fiscale modifie son appréciation sur la situation qui lui a été présentée\n"
        "par le contribuable. L’appréciation antérieure n’est plus\n"
        "valable à partir du jour où le\n"
        "contribuable a été informé de\n"
        "ce changement, et seulement\n"
        "pour l’avenir.\n"
        "8) Le rescrit peut prendre la forme d’un\n"
        "accord avec le contribuable sur la détermination du prix de pleine concurrence concernant une ou plusieurs\n"
        "transactions conformément aux dispositions de l’article 33 du présent\n"
        "Code. L’accord validé par l’Administration fiscale lui est opposable au titre\n"
        "de l’exercice au cours duquel l’accord\n"
        "a été donné et pour les trois (3) exercices suivants. L’Administration fiscale\n"
        "se réserve le droit de dénoncer cet accord lorsqu’il s’avère qu’il a été conclu\n"
        "sur la base d’informations erronées ou\n"
        "incomplètes.\n"
        "9) La prise de position de l’Administration s’applique seulement à la situation individuelle du demandeur et n’est\n"
        "pas opposable par un tiers.\n"
    ),
    "684": (
        "Art. 684.- Est tenue au secret professionnel, tel que défini et sanctionné\n"
        "par le code pénal et l’article 837 du\n"
        "Code Général des Impôts, toute personne appelée, à l’occasion de ses\n"
        "fonctions ou attributions, à intervenir\n"
        "dans la mise en œuvre des règles d’assiettes, de liquidation, de contrôle,\n"
        "d’enquête, de recouvrement ou de\n"
        "contentieux prévues par le Code Général des Impôts. La même obligation\n"
        "s’applique à toute personne qui, en raison de sa relation contractuelle avec\n"
        "l’Administration fiscale, a accès à des\n"
        "renseignements ou documents tenus\n"
        "par l’Administration fiscale quel qu’en\n"
        "soit le support.\n"
        "Toute personne qui accède illégalement aux renseignements ou données\n"
        "détenus par l’Administration fiscale,\n"
        "quel qu’en soit le support, est passible\n"
        "de sanctions prévues en matière de cybercriminalité au Niger.\n"
        "(Modifié par Ordonnance N° 2025-44 du\n"
        "31 décembre 2025 portant Loi de Finances\n"
        "pour l’année budgétaire 2026.)\n"
    ),
    "689": (
        "Art. 689.- 1) Aucune autorité publique\n"
        "ne peut accorder de remise totale ou\n"
        "partielle d’impôts, taxe ou droits prévus par le présent Code, ni en suspendre ou faire suspendre le recouvrement sans en devenir personnellement\n"
        "responsable.\n"
        "2) Sont punis des peines prévues par\n"
        "le Code pénal tous détenteurs de l’autorité publique qui, sous une forme\n"
        "quelconque et pour quelque motif que\n"
        "ce soit, auront, sans autorisation de la\n"
        "loi, accordé toute exonération ou franchise d’impôts, taxes ou droits prévus\n"
        "par le présent Code.\n"
    ),
    "693": (
        "Art. 693.- 1) Le contribuable qui\n"
        "conteste le bien-fondé d’une imposition et en sollicite la décharge ou la\n"
        "réduction, adresse une réclamation au\n"
        "Directeur Général des Impôts ou son\n"
        "représentant.\n"
        "2) Le délai de réclamation est de deux\n"
        "(2) mois à compter de la date :\n"
        "a) de la notification de l’avis de\n"
        "mise en recouvrement ;\n"
        "b) du versement de l’impôt,\n"
        "droit ou taxe contesté lorsque\n"
        "cet impôt, droit ou taxe n’a\n"
        "pas donné lieu à l’établissement d’un avis de mise en recouvrement ;\n"
        "c) du versement des retenues\n"
        "à la source lorsqu’il s’agit de\n"
        "contestations relatives à ces\n"
        "retenues.\n"
        "3) Toute réclamation doit, à peine d’irrecevabilité :\n"
        "a) mentionner le ou les impôts,\n"
        "droits et taxes contestés ;\n"
        "b) être accompagnée d’une copie\n"
        "de l’avis de mise en recouvrement ou d’une quittance dans\n"
        "le cas où l’impôt, droit ou taxe\n"
        "n’a pas donné lieu à l’établissement d’un titre de perception ;\n"
        "c) être appuyée des justificatifs\n"
        "du paiement de la partie non\n"
        "contestée ;\n"
        "d) contenir l’exposé sommaire\n"
        "des moyens et les conclusions du requérant appuyés\n"
        "des pièces justificatives suffisantes ;\n"
        "e) mentionner l’intention du requérant de formuler une demande\n"
        "de sursis de paiement prévue à\n"
        "l’article 694 ci-dessous ;\n"
        "f) être timbrée ;\n"
        "g) être datée et signée du réclamant ou de son mandataire ;\n"
        "h) être appuyée des justificatifs\n"
        "du paiement d’une caution\n"
        "représentant la somme de\n"
        "10% de la partie contestée.\n"
        "4) L’Administration fiscale peut, avant\n"
        "de répondre à la réclamation, demander\n"
        "au contribuable la production de pièces\n"
        "complémentaires. La réponse à cette\n"
        "demande doit lui parvenir dans un délai\n"
        "de huit (8) jours après la notification de\n"
        "celle-ci. À défaut, le service chargé du\n"
        "contentieux traite le dossier en l’état.\n"
        "5) Le Directeur Général des Impôts ou\n"
        "son représentant statue sur les réclamations dans un délai de deux (2) mois\n"
        "à compter de la date de leur présentation. La demande de pièces complémentaires visée au point 4 ci-dessus\n"
        "suspend ce délai pour une durée de\n"
        "huit (8) jours. Le défaut de réponse dans\n"
        "le délai de deux (2) mois vaut décision\n"
        "implicite de rejet de la réclamation.\n"
    ),
}

nb_corriges = 0
for art in articles:
    if art["article_id"] in corrections:
        art["text"] = corrections[art["article_id"]]
        nb_corriges += 1
        print(f"Article {art['article_id']} corrigé ({len(art['text'])} caractères).")

with open(CHEMIN_FICHIER, "w", encoding="utf-8") as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"\n{nb_corriges}/8 articles corrigés (Lot 6).")
