#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
corriger_lot8.py — A LANCER UNE SEULE FOIS depuis le Shell Render.

Lot 8 : articles 801, 808, 810, 813, 818, 827, 836, 855, 856, 868, 870,
871, 872, 873, 877, 1041, 1049.

Note : 855, 871 et 872 n'etaient pas dans la liste initiale des 60 suspects
mais ont ete decouverts contamines en creusant 856/870/873 (contenu de
plusieurs articles entremele). Article 812 verifie egalement au passage :
deja complet, aucune correction necessaire.

Usage :
    python corriger_lot8.py
"""
import json

CHEMIN_FICHIER = "cgi2026_articles_corrige.json"

with open(CHEMIN_FICHIER, encoding="utf-8") as f:
    articles = json.load(f)

corrections = {
    "801": (
        "Art. 801.- 1) Les documents comptables doivent être conservés en République du Niger pendant un délai de\n"
        "dix (10) ans à compter de la date de la\n"
        "dernière opération mentionnée ou de\n"
        "la date à laquelle les documents ont\n"
        "été établis y compris en cas de cessation d’activité de l’entité concernée.\n"
        "Cette obligation couvre notamment :\n"
        "a) les livres comptables et documents de synthèse dont le\n"
        "système comptable de l’Organisation pour l’harmonisation\n"
        "en Afrique du Droit des Affaires\n"
        "impose la tenue ;\n"
        "b) les copies des factures, mémoires, marchés, feuilles d’honoraires, bons de commande,\n"
        "bons de livraison ;\n"
        "c) les documents et registres\n"
        "dont la tenue est prescrite par\n"
        "les actes uniformes de l’Organisation pour l’harmonisation\n"
        "en Afrique du droit des affaires\n"
        "relatifs au droit des sociétés\n"
        "commerciales et au droit commercial général ;\n"
        "d) pour les sociétés ayant un\n"
        "commissaire aux comptes, le\n"
        "rapport prévu par l’article 715\n"
        "de l’Acte uniforme de l’Organisation pour l’harmonisation en\n"
        "Afrique du droit des affaires relatif au droit des sociétés commerciales ;\n"
        "e) pour les sociétés d’assurance,\n"
        "les états prévus par la réglementation de la Conférence interafricaine des marchés d’assurance ;\n"
        "f) toutes autres pièces justificatives des éléments contenus\n"
        "dans les déclarations souscrites au titre de l’exercice de\n"
        "référence.\n"
        "2) La même obligation de conservation\n"
        "s’applique lorsque la comptabilité est\n"
        "informatisée. Le déclarant est en outre\n"
        "tenu :\n"
        "a) de mettre en place des procédures qui permettent de\n"
        "satisfaire aux exigences de\n"
        "régularité, de sécurité, de\n"
        "permanence et de contrôle\n"
        "requises conformément aux\n"
        "dispositions des articles 22\n"
        "et 67 de l’Acte uniforme de\n"
        "l’Organisation pour l’harmonisation en Afrique du droit\n"
        "comptable et à l’information\n"
        "financière ;\n"
        "b) de mettre, à toute réquisition\n"
        "de l’Administration fiscale, à\n"
        "sa disposition les sources du\n"
        "logiciel utilisé.\n"
    ),
    "808": (
        "Art. 808.- 1) Les agents de l’Administration fiscale ayant au moins le\n"
        "grade d’inspecteur ou habilités par le\n"
        "Directeur Général des Impôts peuvent\n"
        "constater par procès-verbal, dont copie est remise à l’intéressé, tout manquement à l’une des obligations visées\n"
        "au présent Code.\n"
        "2) Doivent notamment faire l’objet\n"
        "d’un procès-verbal :\n"
        "a) l’exercice d’une activité sans\n"
        "déclaration d’existence et\n"
        "sans posséder un Numéro\n"
        "d’Identification Fiscale ;\n"
        "b) le défaut de déclaration du\n"
        "changement de domicile ou\n"
        "d’adresse ;\n"
        "c) le défaut de déclaration du\n"
        "changement des caractéristiques de l’exploitation tel\n"
        "que le changement de lieu du\n"
        "siège ou l’ouverture d’un nouvel établissement ;\n"
        "d) l’opposition à un contrôle fiscal ou au contrôle de la facture certifiée ;\n"
        "e) la mention d’un faux Numéro d’Identification Fiscale ou\n"
        "d’une fausse adresse ;\n"
        "f) la mauvaise tenue, la non\n"
        "tenue ou la destruction\n"
        "d’un document comptable,\n"
        "avant l’expiration du délai de\n"
        "conservation ;\n"
        "g) le refus de présentation de\n"
        "tout document dont la production est exigée ;\n"
        "h) le défaut de réponse à une\n"
        "demande écrite dans le délai\n"
        "légal ;\n"
        "i) la mention d’un impôt indirect\n"
        "indu sur une facture ou un document en tenant lieu ;\n"
        "j) le refus de décharger une correspondance administrative ;\n"
        "k) le refus d’exécuter un avis à\n"
        "tiers détenteur ;\n"
        "l) le défaut de délivrance de facture certifiée et tous autres\n"
        "manquements dont peuvent\n"
        "être auteurs les importateurs,\n"
        "fournisseurs, distributeurs\n"
        "de machines électroniques\n"
        "certifiées de facturation, les\n"
        "éditeurs de logiciels et les\n"
        "personnes visées à l’article\n"
        "802 du présent Code.\n"
        "m) l’usurpation d’identité d’autrui à des fins d’émission de\n"
        "factures certifiées frauduleuses ou falsifiées ;\n"
        "n) tout autre manquement faisant l’objet de sanctions prévues au présent Code.\n"
        "3) Le procès-verbal contient, à peine\n"
        "de nullité, les mentions suivantes :\n"
        "a) les nom(s) et prénom(s) et\n"
        "qualité des agents qui ont\n"
        "participé à la constatation\n"
        "des infractions ;\n"
        "b) le lieu, la date et l’heure auxquels il a été rédigé et achevé ;\n"
        "c) les nom et prénoms ou la raison sociale de la personne\n"
        "verbalisée et son adresse ;\n"
        "d) la nature de la constatation\n"
        "ou du manquement, de manière précise ;\n"
        "e) l’indication des dispositions\n"
        "appliquées ;\n"
        "f) la signature de l’agent verbalisateur ;\n"
        "g) la signature du contribuable\n"
        "ou l’indication qu’il a refusé de\n"
        "signer le procès-verbal. Cette\n"
        "mention n’est obligatoire que\n"
        "lorsque le procès-verbal est\n"
        "établi à la suite d’une constatation faite ou d’un manquement relevé durant une intervention sur place.\n"
    ),
    "810": (
        "Art. 810.- 1) Les inexactitudes ou les\n"
        "omissions relevées dans une déclaration ou dans un acte comportant l’indication d’éléments à retenir pour l’assiette ou la\n"
        "liquidation de l’impôt entraînent l’application d’une pénalité d’assiette de 20%\n"
        "aux droits non déclarés.\n"
        "2) Cette pénalité est portée à 40% :\n"
        "a) en cas d’inexactitude relevée\n"
        "dans les documents et renseignements écrits fournis à\n"
        "l’appui de la déclaration du\n"
        "bénéfice réel ;\n"
        "b) si le contribuable n’établit\n"
        "pas sa bonne foi.\n"
        "3) Cette pénalité est portée à 70% :\n"
        "a) en cas de manœuvres frauduleuses prouvées ;\n"
        "b) en cas de facturation illégale\n"
        "ou de détournement de destination de biens ou services\n"
        "acquis en exonération de la\n"
        "taxe sur la valeur ajoutée ;\n"
        "c) en cas de taxation d’office.\n"
        "4) L’annulation ou la rectification d’un\n"
        "crédit de taxe sur la valeur ajoutée\n"
        "suite à un contrôle fiscal, entraînent\n"
        "l’application d’une amende fiscale\n"
        "égale à 80% du montant du crédit de\n"
        "taxe sur la valeur ajoutée remboursé.\n"
        "5) En matière de droits d’enregistrement et de timbres, le montant des pénalités ne peut pas être inférieur à six\n"
        "mille (6 000) francs CFA.\n"
        "6) Excepté le cas où le cumul est expressément prévu, une infraction\n"
        "ne peut donner lieu qu’à une seule\n"
        "amende fiscale, la plus importante.\n"
        "7) Lorsque les omissions ou les\n"
        "inexactitudes relevées dans toute déclaration n’entraînent pas les pénalités\n"
        "proportionnelles prévues au point 1 du\n"
        "présent article, il est fait application,\n"
        "pour chaque renseignement omis ou\n"
        "inexact, d’une amende fixe de vingt\n"
        "mille (20 000) francs CFA.\n"
        "8) Tout contribuable qui n’a pas payé\n"
        "dans les délais légaux les impôts,\n"
        "droits et taxes exigibles, doit verser,\n"
        "indépendamment des pénalités prévues par les articles précédents, un\n"
        "intérêt de retard de 0,25% par mois\n"
        "ou fraction de mois. Cet intérêt court\n"
        "à compter du premier jour du mois\n"
        "suivant celui de l’exigibilité de l’impôt.\n"
        "L’intérêt est calculé sur le montant des\n"
        "droits simples.\n"
    ),
    "813": (
        "Art. 813.- 1) Tout retard dans le paiement de la vignette automobile est\n"
        "sanctionné par l’application au montant dû d’une pénalité de 25% du montant de la vignette.\n"
        "2) Pour les véhicules mis en circulation\n"
        "au cours de l’année, la pénalité est due\n"
        "le premier jour du trimestre suivant celui de l’exigibilité des droits.\n"
        "3) Le défaut de paiement de la vignette\n"
        "automobile entraîne l’immobilisation du véhicule avec le concours des\n"
        "agents chargés de constater les infractions à la circulation routière et sa restitution est subordonnée au règlement\n"
        "de l’impôt dû, y compris les arriérés, le\n"
        "cas échéant.\n"
    ),
    "818": (
        "Art. 818.- 1) Une amende de cent mille\n"
        "(100 000) francs CFA est applicable :\n"
        "a) en cas de défaut ou refus de\n"
        "présentation du certificat\n"
        "d’immatriculation fiscale, aux\n"
        "réquisitions des agents de l’Administrations fiscale ;\n"
        "b) en cas d’absence du Numéro\n"
        "d’Identification Fiscale là où\n"
        "il est requis. Cette amende\n"
        "est portée à deux cent mille\n"
        "(200 000) francs CFA lorsque\n"
        "le contribuable ne régularise\n"
        "pas sa situation dans un délai\n"
        "de trente (30) jours suivant une\n"
        "mise en demeure.\n"
        "c) à tout contribuable qui n’a pas\n"
        "souscrit ou a souscrit hors délai la déclaration d’existence\n"
        "prévue aux articles 774 et 779\n"
        "du Code Général des Impôts.\n"
        "Cette amende est portée à\n"
        "deux cent mille (200 000) francs\n"
        "CFA en cas de défaut de souscription de la déclaration dans\n"
        "un délai de trente (30) jours suivant une mise en demeure et\n"
        "en cas de défaut de notification\n"
        "des informations et documents\n"
        "requis à l’article 774 du Code\n"
        "Général des Impôts ainsi que\n"
        "des modifications intervenues.\n"
        "(Modifié par Ordonnance N° 2025-\n"
        "44 du 31 décembre 2025 portant\n"
        "Loi de Finances pour l’année budgétaire 2026.)\n"
        "2) Une amende d’un million cinq cent\n"
        "mille (1 500 000) francs CFA est applicable à tout contribuable qui aura utilisé son Numéro d’Identification Fiscale\n"
        "à des fins frauduleuses, sans préjudice\n"
        "des sanctions pénales prévues par la\n"
        "loi. En cas d’utilisation frauduleuse\n"
        "du Numéro d’Identification Fiscale à\n"
        "l’insu de son attributaire, les auteurs,\n"
        "co-auteurs et complices sont solidairement responsables du paiement de\n"
        "l’amende, sans préjudice des sanctions pénales prévues par la loi.\n"
    ),
    "827": (
        "Art. 827.- La destruction, avant l’expiration du délai de dix (10) ans, d’un des\n"
        "documents visés à l’article 801 du présent Code, donne lieu à une amende\n"
        "d’un million (1 000 000) francs CFA.\n"
    ),
    "836": (
        "Art. 836.- 1) Seront punis des peines\n"
        "prévues à l’article 185 du Code pénal :\n"
        "a) ceux qui, par violences,\n"
        "voies de faits, menaces ou\n"
        "manœuvres concertées, auront organisé ou tenté d’organiser le refus collectif de\n"
        "payer l’impôt ;\n"
        "b) ceux qui auront refusé collectivement le paiement de l’impôt.\n"
        "2) Sera puni des peines prévues à l’article 349 du Code pénal, sans préjudice des sanctions fiscales prévues à\n"
        "l’article 812 du présent Code :\n"
        "a) celui qui, de mauvaise foi,\n"
        "aura, soit émis un chèque\n"
        "sans provision ou avec provision inférieure au montant\n"
        "du chèque, soit retiré après\n"
        "l’émission du chèque tout ou\n"
        "partie de la provision, soit fait\n"
        "défense au tiré de payer ;\n"
        "b) celui qui, en connaissance\n"
        "de cause, a accepté de recevoir un chèque émis dans les\n"
        "conditions visées ci-dessus.\n"
        "3) Sera puni des peines prévues à l’article 184 du Code pénal, toute personne qui aura refusé de déférer aux\n"
        "réquisitions légales du conservateur\n"
        "de la propriété foncière prévues au\n"
        "présent Code.\n"
        "4) Sera punie des peines prévues à\n"
        "l’article 392 du Code pénal, toute\n"
        "personne qui aura altéré des titres\n"
        "fonciers, des copies de ces titres ou\n"
        "des certificats d’inscription dans les\n"
        "conditions déterminées par cet article.\n"
        "5) Sera puni des peines prévues aux articles 191 et 192 du Code pénal, toute\n"
        "personne qui aura effectué des bris de\n"
        "scellés ou d’affiches dans les conditions prévues par ces articles.\n"
        "6) Sera punie des peines prévues à\n"
        "l’article 142 du Code pénal, toute personne qui aura vendu, distribué ou fait\n"
        "usage de papiers, effets, timbres, marteaux ou poinçons falsifiés ou contrefaits.\n"
    ),
    "855": (
        "Art. 855.- Les marchés exécutés dans\n"
        "le cadre du programme Kandadji de\n"
        "régénération des écosystèmes et de\n"
        "mise en valeur de la vallée du Niger,\n"
        "sont exonérés des impôts et taxes ci-après :\n"
        "a) les droits d’enregistrement et\n"
        "de timbre ;\n"
        "b) la taxe sur la valeur ajoutée.\n"
    ),
    "856": (
        "Art. 856.- 1) Les activités entrant dans\n"
        "le cadre de missions principales de\n"
        "l’Office des Produits Vivriers du Niger\n"
        "sont exonérées des impôts, droits et\n"
        "taxes ci-après :\n"
        "a) la Taxe Professionnelle ;\n"
        "b) l’impôt minimum forfaitaire ;\n"
        "c) la taxe immobilière ;\n"
        "d) la Taxe sur la Valeur Ajoutée ;\n"
        "e) les droits d’enregistrement et\n"
        "de timbre, lorsque les formalités incombent à l’office ;\n"
        "f) les impôts, droits et taxes au\n"
        "cordon douanier à l’exception\n"
        "de la RSI et des prélèvements\n"
        "communautaires.\n"
        "2) Les exonérations prévues au point 1\n"
        "du présent article concernent les produits et matériels ci-après :\n"
        "a) les céréales acquises dans\n"
        "le cadre de la réalisation des\n"
        "activités à caractère social ou\n"
        "humanitaire pour le compte\n"
        "de l’Etat et des partenaires ;\n"
        "b) les produits et matériels de\n"
        "conservation des stocks (produits phytosanitaires, bâches,\n"
        "sacs vides, fils et ficelles, matériels de traitement, palette\n"
        "et bascules) ;\n"
        "c) les camions et les engins de\n"
        "manutention ;\n"
        "d) les véhicules utilitaires légers ;\n"
        "e) les pièces de rechange, les\n"
        "moteurs, les boites de vitesse, les boîtes de transfert\n"
        "et les ponts et essieux pour\n"
        "les camions, les engins de\n"
        "manutention les véhicules\n"
        "utilitaires légers ;\n"
        "f) les pneumatiques et accessoires de pneumatiques pour\n"
        "camions, les engins de manutention, les véhicules utilitaires légers.\n"
        "3) Nonobstant les exonérations prévues au présent article, l’OPVN est\n"
        "tenu au respect des obligations déclaratives.\n"
    ),
    "868": (
        "Art. 868.- Taxe d’extraction\n"
        "1) Le titulaire d’une autorisation d’ouverture et d’exploitation artisanale\n"
        "ou semi-mécanisée de carrière ou\n"
        "d’une autorisation d’exploitation des\n"
        "haldes, des terrils et des résidus d’exploitation de carrière est soumis au\n"
        "paiement d’une taxe d’extraction dont\n"
        "le montant et les modalités de paiement sont fixés par la loi de finances\n"
        "selon le type d’exploitation ;\n"
        "2) La liquidation et le recouvrement\n"
        "de la taxe d’extraction de carrière sont\n"
        "effectués par le Ministère en charge\n"
        "des Mines au profit des collectivités\n"
        "territoriales concernées.\n"
    ),
    "870": (
        "Art. 870.- 1) En période de recherche,\n"
        "les titulaires de permis de recherche\n"
        "et les sociétés de géo-services bénéficient des avantages fiscaux ci-après :\n"
        "a) les titulaires de permis de recherche bénéficient, dans le\n"
        "cadre de leurs activités spécifiques de recherche, de l’exonération de :\n"
        "i) la taxe sur la valeur ajoutée sur :\n"
        "- les importations et les\n"
        "acquisitions en régime\n"
        "intérieur des biens nécessaires à la réalisation des activités minières à l’exclusion des\n"
        "biens exclus du droit à\n"
        "déduction conformément aux dispositions\n"
        "du présent Code ;\n"
        "- les services fournis\n"
        "par les entreprises de\n"
        "géo-services agissant\n"
        "en qualité de sous-traitant.\n"
        "ii) l’impôt sur les sociétés ;\n"
        "iii) l’impôt minimum forfaitaire;\n"
        "iv) la taxe d’apprentissage ;\n"
        "v) la taxe professionnelle ;\n"
        "vi) la taxe immobilière.\n"
        "b) les sociétés de géo-services offrant des services liées aux activités de recherche minière habilitées par le Ministère chargé des\n"
        "mines et travaillant exclusivement pour les sociétés minières,\n"
        "bénéficient de la fiscalité prévue\n"
        "au présent paragraphe à condition qu’elles agissent en qualité\n"
        "de sous-traitant.\n"
        "2) L’exonération des différents impôts\n"
        "et taxes ci-dessus ne fait pas obstacle\n"
        "à l’obligation d’accomplir les formalités de déclaration prévues par la réglementation fiscale en vigueur.\n"
    ),
    "871": (
        "Art. 871.- 1) Pendant la phase de\n"
        "construction de la mine dont la durée\n"
        "ne peut excéder trois (3) ans, les titulaires de titres d’exploitation bénéficient de l’exonération de la taxe sur\n"
        "la valeur ajoutée et des autres impôts\n"
        "dans les conditions prévues par l’article 863 ci-dessus ;\n"
        "2) Les sous-traitants bénéficient des\n"
        "avantages liés à la phase de construction de la mine dans les mêmes conditions pour autant qu’ils répondent aux\n"
        "conditions fixées par la Loi minière ;\n"
        "3) Dans tous les cas, ces exonérations\n"
        "prennent fin à la date de la première\n"
        "production commerciale si celle-ci intervient avant l’expiration du délai de\n"
        "trois (3) ans.\n"
    ),
    "872": (
        "Art. 872.- 1) La stabilité du régime fiscal est garantie au titulaire de titres\n"
        "d’exploitation pendant la durée de validité de la convention et/ou du cahier\n"
        "des charges ;\n"
        "2) Pendant cette période, les règles\n"
        "d’assiette et de liquidation des impôts, des droits et taxes demeurent\n"
        "telles qu’elles existent à la date de signature de la convention ou du cahier\n"
        "des charges ;\n"
        "3) Cette stabilisation ne s’applique\n"
        "pas aux droits fixes et frais d’instruction de dossiers ;\n"
        "4) Sont également exclus du champ de\n"
        "stabilité, les dispositions relatives aux\n"
        "droits humains, à la santé, à la sécurité, à l’emploi, aux aspects environnementaux et sociaux et tous les droits,\n"
        "impôts et taxes y afférents ;\n"
        "5) Nonobstant les dispositions de\n"
        "l’alinéa précédent, en cas d’adoption\n"
        "d’un régime fiscal plus favorable, le\n"
        "titulaire du titre d’exploitation peut\n"
        "opter pour ce régime à condition qu’il\n"
        "l’adopte dans sa totalité.\n"
    ),
    "873": (
        "Art. 873.- La SONICHAR-SA bénéficie pendant toute la durée de la convention de\n"
        "concession de l’exonération des impôts et taxes suivants :\n"
        "a) l’impôt minimum forfaitaire ;\n"
        "b) la taxe sur la valeur ajoutée\n"
        "sur les matériels, matériaux,\n"
        "fournitures, produits, équipements, engins, machines et\n"
        "véhicules destinés exclusivement aux opérations minières,\n"
        "à la production d’énergie électrique ou à la réalisation des\n"
        "missions confiées par l’État ;\n"
        "c) la taxe immobilière ;\n"
        "d) la taxe unique sur les contrats\n"
        "d’assurances sur les installations fixes, les bâtiments, les\n"
        "véhicules et engins destinés\n"
        "exclusivement aux opérations\n"
        "minières ;\n"
        "e) les droits et taxes, à l’exclusion de la taxe intérieure sur\n"
        "les produits pétroliers, sur :\n"
        "i) les combustibles achetés auprès du producteur national ;\n"
        "ii) les combustibles importés.\n"
    ),
    "877": (
        "Art. 877.- 1) Les mutuelles de santé\n"
        "bénéficient de l’exonération des impôts et taxes suivants :\n"
        "a) l’impôt sur les sociétés ;\n"
        "b) l’impôt minimum forfaitaire ;\n"
        "c) la taxe immobilière ;\n"
        "d) la taxe professionnelle ;\n"
        "e) les droits d’enregistrement ;\n"
        "f) la taxe d’apprentissage ;\n"
        "g) la taxe sur la valeur ajoutée ;\n"
        "h) l’impôt sur les revenus des capitaux mobiliers.\n"
        "2) Nonobstant ces exonérations, les\n"
        "mutuelles de santé sont soumises aux\n"
        "obligations déclaratives et celles de\n"
        "retenues à la source.\n"
    ),
}

nb_corriges = 0
for art in articles:
    if art["article_id"] in corrections:
        art["text"] = corrections[art["article_id"]]
        nb_corriges += 1
        print(f"Article {art['article_id']} corrigé ({len(art['text'])} caractères).")

with open(CHEMIN_FICHIER, "w", encoding="utf-8") as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"\n{nb_corriges}/15 articles corrigés (Lot 8).")
print("Note : 1041 et 1049 seront traites dans un lot 9 separe (pas encore examines).")
