#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
corriger_lot2.py — A LANCER UNE SEULE FOIS depuis le Shell Render.

Lot 2 : articles 105, 142, 144, 148, 180, 186.

Usage :
    python corriger_lot2.py
"""
import json

CHEMIN_FICHIER = "cgi2026_articles_corrige.json"

with open(CHEMIN_FICHIER, encoding="utf-8") as f:
    articles = json.load(f)

corrections = {
    "105": (
        "Art. 105- Le taux de la retenue est de 20% du montant hors taxe sur la valeur ajoutée de la rémunération brute.\n"
    ),
    "142": (
        "Art. 142.- 1) Sont également imposables au Niger :\n"
        "a) Les salariés domiciliés au Niger\n"
        "alors même que l’activité rémunérée s’exercerait hors du Niger\n"
        "ou que l’employeur serait domicilié ou résidant hors du Niger.\n"
        "b) Les salariés domiciliés ou résidant hors du Niger, à la double\n"
        "condition que l’activité rétribuée\n"
        "s’exerce au Niger et que l’employeur y soit domicilié ou établi.\n"
        "c) Les fonctionnaires précédemment en service au Niger et jouissant d’un congé administratif\n"
        "hors du Niger. Il en est de même\n"
        "pour les salariés des entreprises\n"
        "privées exerçant leur activité au\n"
        "Niger qui, pendant la durée de\n"
        "leur congé hors du Niger, continuent à être rétribués par l’entreprise à laquelle ils appartenaient\n"
        "avant leur départ en congé.\n"
        "d) Les fonctionnaires ou agents nigériens de l’État et des collectivités territoriales servant dans\n"
        "les pays étrangers où ils sont\n"
        "exemptés d’impôt sur le revenu\n"
        "ou d’un impôt similaire en vertu\n"
        "des dispositions des conventions\n"
        "internationales relatives aux\n"
        "doubles impositions en vigueur.\n"
        "2) Sous réserve des dispositions des\n"
        "conventions internationales relatives\n"
        "aux doubles impositions, sont considérées comme ayant leur domicile fiscal au Niger :\n"
        "a) les personnes qui y possèdent\n"
        "ou y jouissent d’un foyer d’habitation permanent ;\n"
        "b) les personnes qui, sans disposer\n"
        "au Niger d’un foyer d’habitation\n"
        "permanent, ont néanmoins au\n"
        "Niger le centre de leurs intérêts\n"
        "vitaux ;\n"
        "c) dans le cas où les personnes\n"
        "n’ont pas de foyer d’habitation\n"
        "permanent au Niger ou si le\n"
        "centre de leurs intérêts vitaux ne\n"
        "peut pas être déterminé, elles\n"
        "sont considérées comme ayant\n"
        "leur domicile au Niger si elles y\n"
        "séjournent de façon habituelle\n"
        "pendant au moins cent quatre-vingt-trois (183) jours continus\n"
        "ou non sur une période de douze\n"
        "(12) mois.\n"
    ),
    "144": (
        "Art. 144.- 1) Les avantages en nature\n"
        "sont retenus pour leur valeur réelle.\n"
        "2) Toutefois, les avantages en nature\n"
        "suivants sont évalués sur les bases\n"
        "forfaitaires ci-dessous :\n"
        "a) logement : vingt mille (20 000)\n"
        "francs CFA par pièce et par mois\n"
        "dans la limite du 1/3 de la rémunération brute principale ;\n"
        "b) ameublement : 1/3 de la valeur\n"
        "du logement déterminée dans\n"
        "les conditions ci-dessus ;\n"
        "c) électricité : cinquante mille (50 000)\n"
        "francs CFA par mois ;\n"
        "d) eau : quinze mille (15 000) francs\n"
        "CFA par mois ;\n"
        "e) téléphone : vingt mille (20 000)\n"
        "francs CFA par mois ;\n"
        "f) véhicule automobile : vingt mille\n"
        "(20 000) francs CFA par véhicule\n"
        "et par mois ;\n"
        "g) domesticité : vingt mille (20 000)\n"
        "francs CFA par domestique et\n"
        "par mois.\n"
        "h) nourriture : vingt-cinq mille (25 000)\n"
        "francs CFA par mois.\n"
        "3) Par dérogation aux dispositions\n"
        "ci-dessus, les avantages en logement\n"
        "ne peuvent excéder :\n"
        "a) pour les fonctionnaires dont le\n"
        "statut prévoit l’attribution d’un\n"
        "logement, l’indemnité légale\n"
        "prévue par les textes en vigueur ;\n"
        "b) pour les ouvriers des cités minières et industrielles, l’indemnité compensatrice de logement\n"
        "arrêtée de commun accord entre\n"
        "l’employeur et les représentants\n"
        "des travailleurs.\n"
    ),
    "148": (
        "Art. 148.- 1) Pour la détermination\n"
        "du revenu net imposable, il sera tenu\n"
        "compte d’un abattement pour charges\n"
        "de famille dans la limite de sept (7) :\n"
        "a) ses enfants, dans la limite de six\n"
        "(6) :\n"
        "i) mineurs célibataires âgés de\n"
        "21 ans au plus ;\n"
        "ii) infirmes célibataires quel que\n"
        "soit leur âge ;\n"
        "iii) célibataires âgés de 25 ans\n"
        "au plus lorsqu’ils poursuivent\n"
        "leurs études ;\n"
        "iv) l’enfant recueilli dont le parent\n"
        "qui l’a en charge est décédé\n"
        "ou atteint d’une incapacité\n"
        "mentale, sous réserve de la\n"
        "présentation d’un procès-verbal de conseil de famille passé\n"
        "devant une autorité judiciaire.\n"
        "b) un conjoint ne disposant pas de\n"
        "revenu.\n"
    ),
    "180": (
        "Art. 180.- Sont exonérés de l’impôt sur\n"
        "le revenu des capitaux mobiliers :\n"
        "a) les intérêts des sommes inscrites sur les livrets de caisse\n"
        "d’épargne ;\n"
        "b) les intérêts des sommes inscrites\n"
        "sur les comptes d’épargne ou de\n"
        "crédit ouverts dans les écritures\n"
        "des systèmes financiers décentralisés.\n"
        "c) les intérêts, arrérages et autres\n"
        "produits des comptes courants\n"
        "figurant dans les recettes provenant de l’exercice d’une profession industrielle, commerciale,\n"
        "artisanale ou agricole ou d’une\n"
        "exploitation minière sous deux\n"
        "conditions :\n"
        "i) que les contractants aient\n"
        "l’un et l’autre l’une des qualités d’industriel, de commerçant, d’artisan ou d’exploitant\n"
        "agricole ou minier ;\n"
        "ii) que les opérations inscrites\n"
        "au compte courant se rattachent exclusivement à l’activité des deux parties.\n"
        "Les dispositions qui précèdent\n"
        "ne s’appliquent qu’aux\n"
        "contractants dont les intérêts,\n"
        "arrérages et autres produits\n"
        "des comptes courants sont\n"
        "imposés à l’impôt sur les\n"
        "sociétés et à l’impôt sur les\n"
        "bénéfices d’affaires des personnes physiques au Niger.\n"
        "d) les emprunts et obligations des\n"
        "sociétés coopératives de toute\n"
        "nature, quels qu’en soient l’objet\n"
        "et la dénomination.\n"
        "e) les intérêts, arrérages et tous\n"
        "autres produits des rentes, obligations et autres effets publics\n"
        "émis et contractés par l’État et\n"
        "les collectivités locales. Toutefois, cette exonération ne s’applique pas aux entreprises visées\n"
        "au point h) du présent article ;\n"
        "f) les intérêts, arrérages et autres\n"
        "produits de prêts consentis\n"
        "sous une forme quelconque\n"
        "par les personnes exerçant le\n"
        "commerce de banque ou une\n"
        "profession s’y rattachant, ainsi\n"
        "que par les sociétés nigériennes\n"
        "au moyen des fonds qu’elles se\n"
        "procurent en contractant des\n"
        "emprunts soumis eux-mêmes à\n"
        "cet impôt ;\n"
        "g) les intérêts et autres produits de\n"
        "prêts consentis sous une forme\n"
        "quelconque et des dépôts effectués par les associations\n"
        "constituées en vue de mettre à\n"
        "la disposition de leurs membres\n"
        "ou des associations auxquelles\n"
        "elles sont affiliées, les fonds\n"
        "qu’elles se procurent en contractant des emprunts ou en recevant des dépôts. Le montant des prêts exonérés\n"
        "ne peut excéder celui des emprunts contractés ou des dépôts\n"
        "et il doit être justifié par la société, la personne ou l’association ;\n"
        "h) les produits de prêts non représentés par des titres négociables\n"
        "ainsi que les produits visés à\n"
        "l’article 177 du présent Code\n"
        "lorsqu’ils sont encaissés par et\n"
        "pour le compte des banques ou\n"
        "d’établissements financiers, des\n"
        "entreprises de placement ou de\n"
        "gestion de valeurs mobilières\n"
        "ainsi que des sociétés autorisées par l’État à faire des opérations de crédit foncier. Toutefois,\n"
        "cette exonération ne s’applique\n"
        "pas aux produits des opérations\n"
        "réalisées par les personnes ou\n"
        "établissements susvisés au\n"
        "moyen de leurs fonds propres ;\n"
        "i) les intérêts des comptes de dépôts ouverts dans les établissements financiers agréés au Niger\n"
        "par les awqaf publics ou reconnus comme tel conformément\n"
        "au décret n°2025-389/PRN du 18\n"
        "juillet 2025 fixant les conditions\n"
        "générales et les modalités de reconnaissance d’utilité publique\n"
        "du Waqf d’intérêt public.\n"
        "(Modifié par Ordonnance N°\n"
        "2025-44 du 31 décembre 2025\n"
        "portant Loi de Finances pour\n"
        "l’année budgétaire 2026.)\n"
    ),
    "186": (
        "Art. 186.- Le revenu est déterminé :\n"
        "a) pour les sociétés ayant leur siège\n"
        "social au Niger concernant:\n"
        "i) les actions : par le dividende\n"
        "fixé d’après les délibérations\n"
        "des assemblées générales des\n"
        "actionnaires ou des conseils\n"
        "d’administration, les comptes\n"
        "rendus ou tous autres documents analogues;\n"
        "ii) les parts d’intérêts et commandites : soit par les montants\n"
        "distribués lors des délibérations des assemblées générales ou des conseils d’administration, soit à défaut de\n"
        "délibération, au moyen d’une\n"
        "déclaration à souscrire dans\n"
        "les trois (3) mois de la clôture\n"
        "de l’exercice, faisant connaître\n"
        "les bénéfices ou produits effectivement distribués ;\n"
        "iii) les obligations et les emprunts : par l’intérêt ou le revenu distribué dans l’année ;\n"
        "iv) les lots : par le montant du lot\n"
        "en francs CFA ;\n"
        "v) les primes de remboursement:\n"
        "par la différence entre la\n"
        "somme remboursée et le taux\n"
        "d’émission des emprunts ;\n"
        "vi) les rémunérations des administrateurs ou des membres\n"
        "des conseils d’administration: par les délibérations des\n"
        "assemblées générales d’actionnaires ou des conseils\n"
        "d’administration, les comptes\n"
        "rendus et tous autres documents analogues.\n"
        "b) pour les sociétés ne disposant\n"
        "que d’un établissement stable\n"
        "au Niger, par l’intégralité du bénéfice net, sous réserve des dispositions particulières réglées\n"
        "par les conventions fiscales\n"
        "internationales régissant les\n"
        "doubles impositions.\n"
    ),
}

nb_corriges = 0
for art in articles:
    if art["article_id"] in corrections:
        art["text"] = corrections[art["article_id"]]
        nb_corriges += 1
        print(f"Article {art['article_id']} corrigé ({len(art['text'])} caractères).")

with open(CHEMIN_FICHIER, "w", encoding="utf-8") as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"\n{nb_corriges}/6 articles corrigés (Lot 2).")
